name: "finalize and check env"
description: "make the conda env available to future steps and show it"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        source ~/.bash_profile
        echo "micromamba activate pcds-test" >> ~/.bash_profile
    - shell: bash
      run: | 
        source ~/.bash_profile
        mamba list | tee "$GITHUB_TEST_SUMMARY"
