#!/bin/bash
# This is the command the cronjob will run.
# It will call deploy_all and tee the output into a file.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
LOGS="${HERE}/logs"
FILE="${HERE}/logs/$(date -Iseconds)"

if [ ! -d "${LOGS}" ]; then
  mkdir "${LOGS}"
fi

${HERE}/deploy_all $@ 2>&1 | tee ${FILE}
