#!/bin/bash
# pcds_env_deploy
# Script to deploy specific conda envs to hard drive for an LCLS opr

usage()
{
cat << EOF
Usage: $0 [-e ENV] [-i INSTR] [-m] [-d] [-t TARGET]

Deploy a pcds conda env to the operator machine hard drive.
Uses conda_unpack_helper, which uses the conda-pack utility.
Does not require a python environment active.

This deploys environments from NFS at /reg/g/pcds/pyps/conda/packed_envs
to the hard drive at /u1/<instr>opr/envs

Options:
-e ENV:    The environment to deploy. If omitted, we'll deploy latest.
-i INSTR:  The instrument/hutch to deploy for. If omitted, we'll call
           get_hutch_name.
-m :       Memory, deploy to /dev/shm instead of to the HDD
-d :       Dry-run, do not move any files around.
-t TARGET: Install dir override for testing
EOF
}

set -e
CMD=''

while getopts 'e:i:mt:d' OPTION; do
  case "${OPTION}" in
    e)
      ENV="${OPTARG}"
      ;;
    i)
      INSTR="${OPTARG}"
      ;;
    m)
      DISK_DIR="/dev/shm"
      ;;
    t)
      DISK_DIR="${OPTARG}"
      ;;
    d)
      DRY="DRY"
      CMD=echo
      ;;
    ?)
      usage
      exit 0
  esac
done

HERE="$(dirname ${BASH_SOURCE[0]})"
SOURCE_DIR="/reg/g/pcds/pyps/conda/packed_envs"
GET_HUTCH="/reg/g/pcds/engineering_tools/latest/scripts/get_hutch_name"
UNPACK="${HERE}/conda_unpack_helper"

if [ ! -d "${SOURCE_DIR}" ]; then
  echo "${SOURCE_DIR} is missing. Aborting."
  exit 1
fi

if [ ! -x "$(command -v ${UNPACK})" ]; then
  echo "Script conda_unpack_helper not found. Aborting."
  exit 1
fi

if [ -z "${ENV}" ]; then
  TAR_NAME="$(ls ${SOURCE_DIR} | grep pcds | tail -n 1)"
  ENV="$(echo ${TAR_NAME} | cut -d '.' -f 1)"
  SOURCE_TAR="${SOURCE_DIR}/${TAR_NAME}"
  echo "Picked ${ENV}, ${SOURCE_TAR} automatically."
else
  SOURCE_TAR="${SOURCE_DIR}/${ENV}.tar.gz"
  echo "Picked ${SOURCE_TAR} from user arguments."
fi

if [ -z "${DISK_DIR}" ]; then
  if [ -z "${INSTR}" ]; then
    if [ -x "$(command -v ${GET_HUTCH})" ]; then
      INSTR="$(${GET_HUTCH})"
    else
      echo "Script get_hutch_name not found. Aborting"
      exit 1
    fi
  fi
  DISK_DIR="/u1/${INSTR}opr"
fi

UNPACK_DIR="${DISK_DIR}/envs"

if [ ! -d "${DISK_DIR}" ]; then
  echo "Did not find ${DISK_DIR}, something went wrong. Aborting."
  exit 1
fi

if [ ! -d "${UNPACK_DIR}" ]; then
  echo "Creating ${UNPACK_DIR}"
  $CMD mkdir "${UNPACK_DIR}"
fi

UNPACK_ARGS="${UNPACK} -s ${SOURCE_TAR} -u ${UNPACK_DIR}/${ENV}"

if [ -z "${DRY}" ]; then
  $UNPACK_ARGS
else
  $UNPACK_ARGS -d
fi
