#!/bin/bash
# validate_unpack_all
# run validate_unpack on all hosts for a given environment

usage()
{
cat <<EOF
Usage: $0 ENV_NAME

Check all hosts to see if ENV_NAME was installed correctly.
EOF
}

ENV_NAME="${1}"

if [ -z "${ENV_NAME}" ]; then
  usage
  exit 1
fi

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
FILE="${HERE}/hosts.txt"

while read -r line; do
  echo "Validating ${line}"
  ENV_DIR="/u1/${line%%-*}opr/conda_envs/${ENV_NAME}"
  ssh -n "${line}" "${HERE}/validate_unpack ${ENV_DIR}"
done < "${FILE}"

