name: "release notes"
description: "generate the active environment's release notes"
runs:
  using: "composite"
  # Maybe someday default shell will be supported for actions, not just workflows
  # defaults:
  #   run:
  #     shell: bash --login -eo pipefail {0}
  steps:
    - run: conda env export --file envs/pcds/env.yaml
      shell: bash --login -eo pipefail {0}
    - run: |
        cd scripts
        python release_notes_table.py pcds origin/master | tee release_notes_table.txt
        grep -v "^checking " release_notes_table.txt >> "$GITHUB_STEP_SUMMARY"
      shell: bash --login -eo pipefail {0}
